# Generated by Django 4.0 on 2022-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is super user?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
